# Generated by Django 4.1.1 on 2023-02-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('pic_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AUTHORS',
            },
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('podcast_id', models.TextField(blank=True, max_length=16, null=True)),
                ('author_id', models.TextField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'EPISODES',
            },
        ),
        migrations.CreateModel(
            name='PodcastModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('last_episode_id', models.TextField(blank=True, null=True)),
                ('episode_amount', models.IntegerField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('rss_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PODCASTS',
            },
        ),
    ]
