# Generated by Django 4.1.1 on 2023-02-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='podcastmodel',
            table='PODCASTSs',
        ),
    ]
