# Generated by Django 4.1.1 on 2023-02-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_podcastmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='podcastmodel',
            table='PODCASTS',
        ),
    ]
